name: CI-CD

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main, features/add-new-version]

jobs:
  call_eslint:
    uses: ./.github/workflows/lint.yml

  call_build:
    needs: [call_eslint]
    uses: ./.github/workflows/build.yml

  call_test:
    needs: [call_build]
    uses: ./.github/workflows/test.yml
