name: Test

on:
  pull_request:
    branches:
      - main
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  ci-test:
    if: ${{ github.event_name == 'workflow_run' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Run tests
        run: npm test
