name: Test

on:
  workflow_call:

jobs:
  ci-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Run tests
        run: npm test
