name: Test

on:
  workflow_run:
    workflows: [Build]
    types:
      - completed
  pull_request:
    branches:
      - main

jobs:
  ci-test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: latest
      - name: Install dependencies
        run: npm ci
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          github-token: ${{ secrets.GITHUB_TOKEN }}
          run-id: ${{ github.event.workflow_run.id }}
      - name: Run tests
        run: npm test
